### PR TITLE
Fixed dangling javadoc comment warning by applying new mapping

### PR DESCRIPTION
**Pull request by Hakky54**
This is a new PR based on the feedback from this PR: https://github.com/OpenFeign/feign/pull/1557

### CODE REVIEW

**Comment by Hakky54** [comment]
Hi @velo I recreated the pull request with the pom adjustment like you mentioned here: https://github.com/OpenFeign/feign/pull/1557#issuecomment-1014866823

**Review by velo — APPROVED** [review]
Apply license formatter, seems go to go

**Comment by Hakky54** [comment]
Awesome, thank you very much! Any idea why the build is failing. I can't see the logs

**Review by velo — APPROVED** [review]

**Comment by velo** [comment]
> Awesome, thank you very much! Any idea why the build is failing. I can't see the logs

fixed

**Pull request merged**
