### PR TITLE
 Testing feign-example-github jar 

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by kdavisk6** [comment]
An integration test?  I love it

**Comment by kdavisk6** [comment]
@velo 

Could we update the builds to call this manually instead of from Maven to reduce the chances of the API Rate Limit?

**Comment by velo** [comment]
I wanna create an account and include auth so we have a higher rate limit.

but, you know, procrastinating is an art =)

Also, need to change packaging to try to reproduce the original issue that sparkled this change

**Comment by velo** [comment]
@kdavisk6 added a new encrypted github token, now test works on travis

**Pull request merged**
