### PR TITLE
Avoided url appending with slash when matrix parameter exists

### PR DESCRIPTION
**Pull request by ranjitc5**
Fixed an issue of passing matrix parameter using RequestTemplate

More details at  https://github.com/OpenFeign/feign/issues/998

### CODE REVIEW

**Comment by ranjitc5** [comment]
Can anyone please check it ?

**Comment by kdavisk6** [comment]
I’m just back from vacation. I will review this later today also.

**Comment by ranjitc5** [comment]
> Could you also include a unit test? To prevent from breaking again in the future?

**Comment by ranjitc5** [comment]
> Could you also include a unit test? To prevent from breaking again in the future?

I have added UT as well now.

**Pull request merged**
