### PR TITLE
Upgrade httpclient5 to GA version 5.0.3

### PR DESCRIPTION
**Pull request by thanhj**

### CODE REVIEW

**Comment by thanhj** [comment]
Im not sure why all checks failed, my changes don't seem relevant.

**Comment by kdavisk6** [comment]
Files you changed do not have the right license header.  Run `./mvnw license:format` and commit the updated file headers.

**Comment by kdavisk6** [comment]
@thanhj I corrected the headers and updated this for you.

**Review by kdavisk6 — APPROVED** [review]

**Comment by thanhj** [comment]
Thanks! @kdavisk6

**Comment by thanhj** [comment]
@kdavisk6, by the way, when is the next release?

**Pull request merged**
