### PR TITLE
Added fixes for Windows newline handling.

### PR DESCRIPTION
**Pull request by karlnicholas**
Fixes where tests failing on Windows because of newline issues. Most significant change in Jackson/JacksonEncoder.java.

### CODE REVIEW

**Comment by karlnicholas** [comment]
Ughh.

**Comment by karlnicholas** [comment]
Oops, closed wrong one.

**Comment by spencergibb** [comment]
I disagree that changing implementation details is the right way to fix tests on Windows

**Comment by karlnicholas** [comment]
Closing because I merged in the pom.xml changes. I want to make two separate PR's. Sorry for stupid GIT use.

**Pull request closed without merging**
