### PR TITLE
Make logRetry() and logIOException() protected

### PR DESCRIPTION
**Pull request by rfalke**

### CODE REVIEW

**Comment by rfalke** [comment]
Fix for #468

**Comment by adriancole** [comment]
I see your point. we usually don't open things until they are asked for, and in this case I don't see any harm doing so.

**Comment by EXPEkmajewski** [comment]
I am also interested in consuming this fix. Any idea when it will be released? Thanks.

**Comment by rfalke** [comment]
Well it is not in 9.3.1. No idea when the next version will be created.
@adriancole ?

**Comment by adriancole** [comment]
9.4 on the way now! thanks for the nag

**Pull request merged**
