### PR TITLE
Exchange "Produces" and "Consumes"

### PR DESCRIPTION
**Pull request by chengda**
The annotation "ResponseBody" means that the return value of the controller method is a JSON, so it should be right to call the method "handleProducesAnnotation" . 
The annotation "RequestBody" means that the parameter of the controller method is a JSON, so it should be right to call the method "handleConsumesAnnotation" .

### CODE REVIEW

**Review by velo — CHANGES_REQUESTED** [review]
Can we get some testing for this?!

**Comment by chengda** [comment]
> Can we get some testing for this?!

Yes, you can test it . In my project, i met a problem about this , so i debugged it  and modify some codes like that, then i solved the problem.

**Comment by chengda** [comment]
> Can we get some testing for this?!

One of my controller is like this:
`
@PostMapping(value="/test", produces="plain/text")
public String test(){
 ...
}
`
Before the modification，the request header 'Accept' that feign generated is 'application/json'; After the modification, it became 'plain/text'.

**Review by velo — CHANGES_REQUESTED** [review]
Please include a unit test covering the change

**Comment by chengda** [comment]
> Please include a unit test covering the change
Ok, it's done, please check it.

**Review by velo — APPROVED** [review]

**Pull request merged**
