### PR TITLE
Allow multiple inheritance on the interface level with current restrictions intact

### LINKED ISSUE #1284: FEATURE REQUEST:Multi Level Multiple Inheritance and Override Support
WIP still working on the issue and its associated PR, please bear with me

### Multi Level (Generic) Inheritance  With Multiple Inheritance Support at the Second (and Higher) Level And Generic Method Override

Here, the feign client interface `SomeServiceClientApi` inherits from the interface `SomeService`, which then inherits from multiple other (generic) interfaces, sharing its interface with the `SomeServiceApiController`  rest controller via the `SomeService` interface.

```
interface RetrieveService<T> {
  T retrieve(String key);
}

interface StatusService {
  String status();
}

interface SomeService extends RetrieveService<String>, StatusService {
}

@FeignClient
interface SomeServiceClientApi extends SomeService {
   @GetMapping("/retrieve/{key}", produces="text/plain")
   @Override
   String retrieve(@PathVariable("key") String key);

   @GetMapping("/status", produces="text/plain")
   @Override
   String status();
}

@RestController
class SomeServiceApiController implements SomeService {

  @GetMapping("/retrieve/{key}", produces="text/plain")
  @Override
  @ResponseBody
  public String retrieve(@PathVariable("key") String key) { ... }

  @GetMapping("/status", produces="text/plain")
  @Override
  @ResponseBody
  String status() { ... }
}
```

or, alternatively (and most provably in combination with the above)

```
interface RetrieveService<T> {
  T retrieve(String key);
}

interface StatusService {
  String status();
}

interface SomeService extends RetrieveService<String>, StatusService {
}

interface SomeServiceApiBase extends SomeService {
   @GetMapping("/retrieve/{key}", produces="text/plain")
   @ResponseBody
   @Override
   String retrieve(@PathVariable("key") String key);

   @GetMapping("/status", produces="text/plain")
   @ResponseBody
   @Override
   String status();
}

@FeignClient
interface SomeServiceClientApi extends SomeServiceApiBase {
}

@RestController
class SomeServiceApiController implements SomeServiceApiBase {

  @Override
  // going for the naive Spring will fixit approach here, alternatively one must repeat the `@PathVariable` annotation
  // on the formal method parameter here
  public String retrieve(String key) { ...; }

  @Override
  public String status() { ...; }
}
```

### Decomposition of the Service Interface for both Testing and Delegation Purposes

A so composed service interface can be decomposed so that one can test indiividual features of a service a/o client using shared (generic) test classes a/o strategies, when considering standard CRUD and other operations.

One could also use delegates on the server side to realize specific facets of the service interface, e.g. one that will realize the `status` and one that will realize the `retrieve`, and so on.

And while the Spring framework already provides for such, Feign will currently prevent this from happening as it does not support multiple inheritance on the interface level. Basically meaning that one cannot have a service interface that is shared between both the client and the server without having to redeclare the client interface.

## Positive Side Effects

- overriding methods from (parameterized) base interfaces is now supported

## Implementation Notes

Since `spring-cloud-openfeign` does override some of the `process*` methods from `Contract.BaseContract`, I resorted to just detecting when multiple methods with the same key are available.

Annotations on base interfaces, except for when it is the first inherited one, are simply ignored.

Additional test cases have been introduced that provide for a basic safeguard but do not realize every possible combination.

## Additional Information

spring-cloud-openfeign must be updated so as to use the new version.

## PR

#1285 

## See also

#320, #1244, #1029

### PR DESCRIPTION
**Pull request by silkentrance**
fixes #1284

### CODE REVIEW

**Comment by silkentrance** [comment]
@kdavisk6 still not getting a circleci detail link on the build... darn

**Comment by silkentrance** [comment]
Tests are working just fine locally:  https://gist.github.com/silkentrance/419a6a7e38032d0f2e33e4d0a46844c8

**Comment by kdavisk6** [comment]
For some reason the webhook for your Pull request is being rejected by Circle CI.  The hook response indicates a `400`, but not sure why.  Others have been able to push changes to their branches and have it work.  We'll leave it for now.

**Comment by silkentrance** [comment]
moving on and waiting for your input.

**Comment by MastaP** [comment]
Hi, any chance to get this PR fixed and merged?

**Comment by silkentrance** [comment]
rebased to master, conflicts have been resolved

**Comment by silkentrance** [comment]
@kdavisk6 the build fails on jdk8, complaining about a missing Path class from the javax.ws.rs package.

**Comment by kdavisk6** [comment]
@silkentrance 

Having read through this, I don't see anything that I feel the need to comment on.  However, the changes are in our type handling and it will be very difficult to see what affect this will have on existing projects.  It's a risky change, but I do see the value.  

I looked over the build and it looks like there is something off with your fork.  I recommend rebasing instead of merging with the latest master.  Once the tests are green, we can look into merging.

**Comment by silkentrance** [comment]
@kdavisk6 i did a rebase but there were some editing conflicts in the files i had been changing, so no biggie.

**Comment by silkentrance** [comment]
I just did a new rebase. Let's see what circle ci has to say about this.

Building this locally with `mvn -Pjava11,release[,windows,ossrh] clean compile test` succeeded. The same is true for a build without the `java11` profile enabled.

I am using openjdk 14.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Feign (Parent) 10.13-SNAPSHOT:
[INFO]
[INFO] Feign (Parent) ..................................... SUCCESS [  5.243 s]
[INFO] Feign Core ......................................... SUCCESS [ 40.522 s]
[INFO] Feign Gson ......................................... SUCCESS [  3.701 s]
[INFO] Feign JAX-RS ....................................... SUCCESS [  4.175 s]
[INFO] Feign Apache HttpClient ............................ SUCCESS [  4.400 s]
[INFO] Feign JAX-RS 2 ..................................... SUCCESS [  6.121 s]
[INFO] Feign Apache HttpComponents Client 5 ............... SUCCESS [  6.797 s]
[INFO] Feign Hystrix ...................................... SUCCESS [  6.938 s]
[INFO] Feign Jackson ...................................... SUCCESS [  4.570 s]
[INFO] Feign Jackson JAXB ................................. SUCCESS [  4.000 s]
[INFO] Feign JAXB ......................................... SUCCESS [  4.423 s]
[INFO] Feign OkHttp ....................................... SUCCESS [  4.098 s]
[INFO] Feign Google HTTP Client ........................... SUCCESS [  4.650 s]
[INFO] Feign Ribbon ....................................... SUCCESS [  7.422 s]
[INFO] Feign SAX .......................................... SUCCESS [  3.585 s]
[INFO] Feign SLF4J ........................................ SUCCESS [  3.325 s]
[INFO] Feign Mock ......................................... SUCCESS [  4.190 s]
[INFO] Feign spring ....................................... SUCCESS [  4.393 s]
[INFO] Feign SOAP ......................................... SUCCESS [  4.807 s]
[INFO] Feign Reactive Wrappers ............................ SUCCESS [  7.121 s]
[INFO] Feign Dropwizard Metrics4 .......................... SUCCESS [  3.679 s]
[INFO] Feign Dropwizard Metrics5 .......................... SUCCESS [  3.443 s]
[INFO] Feign Micrometer ................................... SUCCESS [  3.802 s]
[INFO] GitHub Example ..................................... SUCCESS [  2.088 s]
[INFO] Wikipedia Example .................................. SUCCESS [  2.106 s]
[INFO] Feign APT test generator ........................... SUCCESS [  6.026 s]
[INFO] Feign Benchmark (JMH) .............................. SUCCESS [  4.038 s]
[INFO] Feign Java 11 ...................................... SUCCESS [  2.905 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by silkentrance** [comment]
@kdavisk6 again failing on jdk8.

I found this https://stackoverflow.com/questions/10869977/cant-find-javax-ws-rs-package-in-jdk which states that javax-ws-rs is not part of that jdk.

**Comment by silkentrance** [comment]
just went through the hassle and installed openlogic openjdk 8 x64 for windows

```
$ /p/development/maven/bin/mvn -X -U -Prelease clean compile test
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: P:\development\maven
Java version: 1.8.0-262, vendor: OpenLogic-OpenJDK, runtime: P:\development\jdks\openlogic-openjdk-8u262-b10-win-64\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

and it also fails on the JAXRS2ContractTest.

**Comment by silkentrance** [comment]
Retrying this with the master (with latest changes from upsteam) does not fail :smile:.
I wonder what went wrong during the rebase to gh-1284.

**Comment by silkentrance** [comment]
Okay, this was due to IntelliJ expanding the wildcard import from javax.ws.rs. I have reverted these changes and was able to eliminate changes to otherwise unrelated files.

**Comment by silkentrance** [comment]
@kdavisk6 everything seems to be working now, see previous comment.

**Comment by silkentrance** [comment]
rebased to master

**Comment by silkentrance** [comment]
@kdavisk6 what about integrating this into the master branch and make this part of the forthcoming release?

**Review by velo — APPROVED** [review]
Seem Kevin was happy with the change, and so am I.

I agree can be risky, but, didn't conflict on any of my projects, so thumbs up

**Pull request merged**
