### PR TITLE
feat: added validation for duplicated keys on header

### PR DESCRIPTION
**Pull request by efres**
# What: 
Problem described on [Issue 1361](https://github.com/OpenFeign/feign/issues/1361)

# Why:
To fix integration and requests problems with the interceptor.

# Action:
Added validation to remove the previous header set.

### CODE REVIEW

**Comment by evertonsegurzup** [comment]
(RFC-2616)[https://tools.ietf.org/html/rfc2616#section-4.2]
```
Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.
```

**Comment by evertonsegurzup** [comment]
[RFC-7230](https://tools.ietf.org/html/rfc7230#section-3.2.2)

```
A sender MUST NOT generate multiple header fields with the same field name in a message unless either the entire field value for that header field is defined as a comma-separated list [i.e., #(values)] or the header field is a well-known exception (as noted below).

A recipient MAY combine multiple header fields with the same field name into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field value to the combined field value in order, separated by a comma. The order in which header fields with the same field name are received is therefore significant to the interpretation of the combined field value; a proxy MUST NOT change the order of these field values when forwarding a message.
```

**Comment by kdavisk6** [comment]
@efres Please see my comments on this issue.  This is by design and not a bug.

**Comment by efres** [comment]
@kdavisk6 ok. I'll answer there. Thanks

**Pull request closed without merging**
