### PR TITLE
Fix illegal HTTP status code

### LINKED ISSUE #1773: Illegal HTTP status code when IOException thrown
When external service is unavailable, or just not respond, SynchronousMethodHandler throws RetyableException with HTTP status code -1. The reference from master branch below.
```java
try {
      response = client.execute(request, options);
      // ensure the request is set. TODO: remove in Feign 12
      response = response.toBuilder()
          .request(request)
          .requestTemplate(template)
          .build();
    } catch (IOException e) {
      if (logLevel != Logger.Level.NONE) {
        logger.logIOException(metadata.configKey(), logLevel, e, elapsedTime(start));
      }
      throw errorExecuting(request, e);
    }
```
and the status:
```java 
static FeignException errorExecuting(Request request, IOException cause) {
    return new RetryableException(
        -1,
        format("%s executing %s %s", cause.getMessage(), request.httpMethod(), request.url()),
        request.httpMethod(),
        cause,
        null, request);
 }
```

**The problem:** 
It's _really_ hard to find because we even can't obtain response body due to unsupported numeric data type (negative).  In our case, we seen status code 65535 in Google Chrome (I assume Google Chrome use an unsigned short int datatype for http status code), what makes debug much more difficult. Tested on Postman, Windows PowerShell, Google Chrome v.101, cURL.

**The solution:**
So I'm offering to throw by default 500 (or maybe 0, if you don't want to throw an existing http status code) and provide an ability to customize this parameter. I'd be glad to fix it by myself.

### PR DESCRIPTION
**Pull request by Regyl**
Changes:
- Add connectExceptionStatus to the Options class which contains configurations for each FeignClient
- Switch from wrong status code to the connectExceptionStatus above (by default 500)
- Add tests

Fixes #1773

### CODE REVIEW

**Review by velo — CHANGES_REQUESTED** [review]
Sorry, I don't think it's reasonable to assign an http response code when there was no http connection... 

Why is that necessary?

**Comment by Regyl** [comment]
We have an exception handler where we parse response status code from feign exception like below:
```ava
   @ExceptionHandler(FeignException.class)
    public ErrorResponse handleFeignClientException(FeignException feignException, HttpServletResponse response) {
        response.setStatus(feignException.status());
    }
```
But when feign client throws exception with status code -1, we can't read the entire response. That makes debugging much more difficult (faced this problem on production).
You're right, there is no http connection. So how about send 0 as a status code?
In this case we won't send the correct http response status (not a part of RFC 2068) and simplify debugging for users.

**Comment by velo** [comment]
> So how about send 0 as a status code?

Wouldn't 0 also be a invalid case too and cause the same issue? In any case, I would prefer to avoid breaking compatibility, as people may be using -1 already.

I think the correct answer on example above is for you to translate that -1 into 500.... or 503.

I don't think feign can say what is the appropriate code for everyone out there.

**Comment by Regyl** [comment]
The general message that almost all tools whose interacting with HTTP couldn't read response if status code is _negative_.
I agree, this can broke someone's mechanism. To avoid crunches like checking status, can we add an ability to customize this value (e.g. from application.properties for Spring Boot) and set by default -1 if not specified another?

**Comment by kdavisk6** [comment]
> The general promise that almost all tools whose interacting through HTTP couldn't read response if status code is _negative_. I agree, this can broke someone's mechanism. To avoid crunches like checking status, can we add an ability to customize this value (e.g. from application.properties for Spring Boot) and set by default -1 if not specified another?

>
>```java
> @ExceptionHandler(FeignException.class)
>  public ErrorResponse handleFeignClientException(FeignException feignException, HttpServletResponse response) {
>     response.setStatus(feignException.status());
>}
>```

This doesn't really fit with how Feign works.  Feign is not an HTTP client, so it doesn't need to adhere to HTTP standards.  It's our intention that you use an `ErrorDecoder` to produce your own exceptions from Feign's processing loop.

**Comment by Regyl** [comment]
In this case ErrorDecoder didn't invoke. If I right checking response status on negative values the only way for me. This is correct behavior and you won't gonna change it?

**Comment by velo** [comment]
> In this case ErrorDecoder didn't invoke. If I right checking response status on negative values the only way for me. This is correct behavior and you won't gonna change it?

well, in this case, there was no HTTP connection at all.... that is why feign is reporting a "-1 I don't know what is going on"

**Comment by Regyl** [comment]
Have no questions anymore. Thank you for patience and explanation so much!

**Pull request closed without merging**
