### PR TITLE
Updated POM to set compiler and signatures to Java 8

### PR DESCRIPTION
**Pull request by kdavisk6**
* Updated the Cipher Suites in `TrustingSSLSocketFactory` to an appropriate
Java 8 Cipher.  
* Updated Versions to 10.0.0-SNAPSHOT

In support of #656

### CODE REVIEW

**Comment by velo** [comment]
Now, shall we include retro lambda on this and at least try to keep java 6 support for a while, or just drop it?

**Comment by kdavisk6** [comment]
I think that would a good start.

**Comment by velo** [comment]
Absolutely.

I branched `9.x`

May be, just create a ticket about `retrolambda` and see if anyone expressed the desire to make it happen.

**Comment by spencergibb** [comment]
I don't think you need retro lambda. If they need six, use the 9.x branch.

**Pull request merged**
