### PR TITLE
Multi Level Multiple Inheritance and Override Support

### PR DESCRIPTION
**Pull request by silkentrance**
*WIP* please review and comment!

## See Also

#1284

### CODE REVIEW

**Comment by silkentrance** [comment]
The command "./travis/no-git-changes.sh" exited with 1.

why is that? what is needed to make the build, which otherwise succeeeded flawlessly, not fail?

**Comment by kdavisk6** [comment]
Thank you for your work on this.  I will need some time to read through and review this completely.  This has been attempted a few times before and has proved difficult to get right.  I will need a few days.

**Comment by silkentrance** [comment]
@kdavisk6 TIA for your review. Please note that the current build fails due to some deactivated modules. I also have an issue with a license header somewhere which I was unable to resolve. I will try to get the build working again soon.

**Comment by silkentrance** [comment]
@kdavisk6 I have reestablished the original pom parent and reenabled formely disabled modules and plugins. Please comment on the existing PR.

**Comment by silkentrance** [comment]
rebased to upstream/master

**Comment by silkentrance** [comment]
local builds are failing due to Cannot resolve plugin com.spotify:docker-maven-plugin:<unknown>

**Comment by kdavisk6** [comment]
The `docker` usage comes from the experimental Annotation Processor project.  I'll look into what I can do, but for now I recommend removing the `<module>apt-test-generator</module>` from the parent pom.

**Comment by silkentrance** [comment]
@kdavisk6 i do not get any response from the build check...

**Comment by silkentrance** [comment]
@kdavisk6 I get the error about the missing plugin version only when running maven from inside IntelliJ.... and that poses a lot of different other problems, too. Running the tests from the console seems to working just fine.

**Comment by kdavisk6** [comment]
WRT to the build checks, I've had to move our build system from Travis to CircleCI since the version of Travis we are using is shutting down.  Please ensure that you have a `.circleci` folder in your workspace.  The check will begin working again once the Circle Ci configuration is present in your fork.

**Comment by silkentrance** [comment]
@kdavisk6 circleci confiiguration is present

rebased to current master

**Comment by kdavisk6** [comment]
I'm not sure why the "old" build check is set for your branch.  I'll temporarily disable the required check and see if that updates this Pull Request.

**Comment by silkentrance** [comment]
I'll do a force push.

**Comment by silkentrance** [comment]
On second though, I will wait a bit longer for the forced push.

**Comment by silkentrance** [comment]
@kdavisk6 BTW what are your experiences with this PR? does it work out or does it fail under edge conditions?

**Comment by kdavisk6** [comment]
I apologize, I have not been able to give this change the attention it deserves.  I've been heads down on the Travis retirement over the holidays.  I have a few more housekeeping tasks to complete this week and then I'll shift my attention to this.

**Comment by silkentrance** [comment]
Take your time.

Just to mention, I have a project here (private) that uses multiple inheritance at the second level and it works just fine, keeping the original contract (one interface, one super interface) intact.

**Comment by silkentrance** [comment]
I will close this PR and open up a new one, since the build check is not working.

**Pull request closed without merging**
