### PR TITLE
@Path("") annotations are equivalent to @Path("/")

### PR DESCRIPTION
**Pull request by cakofony**
The documentation suggests that all paths are relative:
https://docs.oracle.com/javaee/6/api/javax/ws/rs/Path.html

### CODE REVIEW

**Comment by cakofony** [comment]
This change resolves #630

**Comment by kdavisk6** [comment]
This looks good to me.  I suggest adding some changes to the documentation as well.  Right now the README calls this situation out explicitly as something that will throw an `IllegalStateException`.  See [JAXRS Readme](https://github.com/OpenFeign/feign/blob/master/jaxrs/README.md)

**Comment by cakofony** [comment]
Great catch @kdavisk6, thanks! Fixed.

**Comment by kdavisk6** [comment]
Approved from my point of view.  @velo any additional feedback?

**Comment by velo** [comment]
Nop, good to go

**Pull request merged**
