### PR TITLE
Add POST example to README.md and example-github

### PR DESCRIPTION
**Pull request by eiselems**
Fixes: #978

### CODE REVIEW

**Comment by wulftone** [comment]
Looks like a good example! I think it might help people to let them know explicitly that the parameter order matters, or they'll just get confused about it.. e.g. in development they might make a GET method with some params, then change it to a POST and add a third body parameter, which is wrong, then read the readme again and maybe notice the subtlety. I prefer spelling it out in sentences that this ordering is a hard requirement.

**Comment by eiselems** [comment]
Good point. Since I am a bit spoiled since I use SpringBoot together with spring-feign ...
how would I do the following with just openFeign?

```
@RequestMapping(method = RequestMethod.POST, value = "/stores/{storeId}", consumes = "application/json")
Store update(@PathVariable("storeId") Long storeId, Store store);
```

@kdavisk6 mentioned the @body annotation, but that requires a templated body which is not what I want here 😕 ? Anybody could shine some light on it?


Also: Just took this from the spring cloud example page, there it seems that the order is not important - which I find slightly interesting.

**Comment by kdavisk6** [comment]
`@Body` can be used two ways, one on the method with a template, the other is on a parameter.  To take your example and convert it to vanilla feign:

```java
@RequestLine("POST /stores/{storeId}")
@Header("Content-Type: application/json")
Store update(@Param("storeId") Long storeId, @Body Store store);
```
The information missing from the documentation is that `@Body` can be omitted if the last parameter in the method signature is the request body.  @eiselems, your intuition about the parameter location is on point.  

Here is an example where the `@Body` is required.

```java
@RequestLine("POST /stores/{storeId}/item/{item}")
@Header("Content-Type: application/json")
Store update(@Param("storeId") Long storeId, @Body Store store, @Param("item") Long item);
```
Hope this helps.

**Comment by kdavisk6** [comment]
@velo @eiselems 

Not sure why Travis is not running the build.  It's breaking on the environment set up, however there are no environment changes in this PR.  Either of you have any insight on what we should look for to fix?  I kicked Master just to see if it something in the repo, but that build is working just fine.

**Comment by eiselems** [comment]
Don't stress the build, not in a hurry to merge this asap. Take your time for figuring it out.

@kdavisk6 what is confusing me is that the interface approach doesn't work on my machine.
It is complaining that @Body requires a parameter and is not applicable to a parameter, is there another @Body for parameters which is not on the buildPath of the example?

**Comment by velo** [comment]
> @velo @eiselems
> 
> Not sure why Travis is not running the build. It's breaking on the environment set up, however there are no environment changes in this PR. Either of you have any insight on what we should look for to fix? I kicked Master just to see if it something in the repo, but that build is working just fine.

I think is travis failing to install java... let's retry in a day or 2.

**Comment by eiselems** [comment]
@kdavisk6 Sorry for probably needing too much hand holding for this one ...

I discovered in the example that all of:
```
@RequestLine("POST /repos/{owner}/{repo}/issues")
void createIssue(@Param("owner") String owner, Issue issue, @Param("repo") String repo);
```

**Comment by eiselems** [comment]
So I think in the current state it should be good to merge

**Comment by wulftone** [comment]
Huh. I definitely encountered issues if the pojo wasn't first in the list. I'll have to dig a little to find out why that is...

**Comment by kdavisk6** [comment]
I found the issue with the build, so I'm going to fix that in another PR before the end of the week.  I'm ok with passing on that check for now.

@wulftone If you want, please create an issue asking for clarification on how to use the `@Body` parameter so we can track it.

**Pull request merged**
