### PR TITLE
Add http_method tag to micrometer metrics

### PR DESCRIPTION
**Pull request by rnavarropiris**
Add HTTP method information as tag for micrometer HTTP requests.

### CODE REVIEW

**Comment by rnavarropiris** [comment]
Addresses: https://github.com/OpenFeign/feign/issues/1631

**Review by velo — APPROVED** [review]
I'm happy with the change, we just need to have CI happy too

**Comment by rnavarropiris** [comment]
Thanks @velo!
I did see some syntax related error reported. I imported the eclipse settings into IntelliJ and reformatted the reported file, but the error persist.

Since I'm not sure what else could be wrong and I didn't see any troubleshooting notes ( I checked README, CONTRIBUTING & HACKING),  could you lend me a hand/give me a hint? :)

**Comment by velo** [comment]
Did you build the project locally?

**Comment by rnavarropiris** [comment]
@velo 
I tried (`mvn package`), but stumble against this error:

```
[ERROR] No plugin found for prefix 'feign-example-github' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/.../.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
org.apache.maven.plugin.prefix.NoPluginFoundForPrefixException: No plugin found for prefix 'feign-example-github' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/.../.m2/repository), central (https://repo.maven.apache.org/maven2)]
```

Seems to happen when executing the task `:feign-example-github` :/

**Pull request merged**
