### PR TITLE
Use travis to enforce code format

### PR DESCRIPTION
**Pull request by velo**
I just build feign locally and lot's of files got reformatted.

Will enforce it on travis... again =)

### CODE REVIEW

**Comment by velo** [comment]
My first attempt did not work, as the build should have failed =((

**Comment by velo** [comment]
Sweet, got a failing build
```
0.02s$ ./travis/no-git-changes.sh
3616++git status --porcelain
3617+'[' -z M core/src/main/java/feign/Client.java M core/src/main/java/feign/FeignException.java M core/src/test/java/feign/FeignExceptionTest.java M core/src/test/java/feign/RetryerTest.java M core/src/test/java/feign/client/DefaultClientTest.java M googlehttpclient/src/main/java/feign/googlehttpclient/GoogleHttpClient.java M googlehttpclient/src/test/java/feign/googlehttpclient/GoogleHttpClientTest.java '??' core/1.log.1 '??' core/1.log.1.lck '??' core/1.log.2 '??' core/1.log.2.lck '??' core/1.log.lck '??' core/2.log.1 '??' core/2.log.1.lck '??' core/2.log.2 '??' core/2.log.2.lck '??' core/2.log.lck ']'
3618./travis/no-git-changes.sh: line 21: [: too many arguments
3619+echo 'The following files have formatting changes:'
3620The following files have formatting changes:
3621+git status --porcelain
3622 M core/src/main/java/feign/Client.java
3623 M core/src/main/java/feign/FeignException.java
3624 M core/src/test/java/feign/FeignExceptionTest.java
3625 M core/src/test/java/feign/RetryerTest.java
3626 M core/src/test/java/feign/client/DefaultClientTest.java
3627 M googlehttpclient/src/main/java/feign/googlehttpclient/GoogleHttpClient.java
3628 M googlehttpclient/src/test/java/feign/googlehttpclient/GoogleHttpClientTest.java
3629?? core/1.log.1
3630?? core/1.log.1.lck
3631?? core/1.log.2
3632?? core/1.log.2.lck
3633?? core/1.log.lck
3634?? core/2.log.1
3635?? core/2.log.1.lck
3636?? core/2.log.2
3637?? core/2.log.2.lck
3638?? core/2.log.lck
3639+echo ''
```

**Comment by finnetrolle** [comment]
I see files my tests create. Something wrong with them?

**Comment by velo** [comment]
> I see files my tests create. Something wrong with them?

Well, I would say creating test files along side with sources could lead to anyone pushing it into git. And that would be terrible.

@finnetrolle  Can you point out to me how to change the location where this tests write to?

**Comment by finnetrolle** [comment]
> > I see files my tests create. Something wrong with them?
> 
> Well, I would say creating test files along side with sources could lead to anyone pushing it into git. And that would be terrible.
> 
> @finnetrolle Can you point out to me how to change the location where this tests write to?

Here is the path declaration feign/MultipleLoggerTest.java:29
Yes, you right about possibility of pushing test files with code. Looks like we need to delete them after test or move into another directory

**Comment by velo** [comment]
thanks @finnetrolle

**Pull request merged**
