### PR TITLE
Add retry feature to async feign

### LINKED ISSUE #1758: Add retry feature to async feign
- related: #361
- pre-work
  - #1754
    - Eliminates the possibility of breaking changes following AsyncFeign's refactoring in advance
  - #1755
  - #1756

### PR DESCRIPTION
**Pull request by wplong11**
Resolves #1758
Contains #1756 PR commits

### CODE REVIEW

**Review by velo — APPROVED** [review]

**Review by velo — APPROVED** [review]
@kdavisk6 do you want to take a look too?

I think this will break binary compatibility, so, major release?

**Comment by wplong11** [comment]
@velo What classes are you concerned about breaking binary compatibility?(I know a little about Java binary compatibility) If you're concerned about breaking binary compatibility for the Async feature, isn't it ok because it's experimental?

**Comment by velo** [comment]
> @velo , isn't it ok because it's experimental?

Yeah, it's ok. But, there will be complaints:/

**Comment by wplong11** [comment]
@velo What changes break AsyncFeign's Binary Compatability? If the change from abstract to final is a problem, how about removing the final keyword? After that, how about adding the final keyword as a separate PR?

**Pull request merged**
